# Generated by Django 3.0.8 on 2020-08-05 06:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hardware',
            fields=[
                ('hardwareId', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='硬件ID')),
                ('CPU', models.IntegerField(verbose_name='cpu')),
                ('memory', models.IntegerField(verbose_name='内存')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('proId', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='项目id')),
                ('parentId', models.IntegerField(verbose_name='父项目id')),
                ('ancestors', models.CharField(max_length=50, verbose_name='祖级列表')),
                ('proName', models.CharField(max_length=50, verbose_name='项目名称')),
                ('orderNum', models.IntegerField(verbose_name='显示顺序')),
                ('leader', models.CharField(max_length=20, verbose_name='负责人')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('status', models.CharField(max_length=1, verbose_name='项目状态（0正常 1已下线 2测试中）')),
                ('createBy', models.CharField(max_length=64, verbose_name='创建人')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('hostId', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='主机ID')),
                ('hostName', models.CharField(max_length=50, verbose_name='主机名称')),
                ('hostOs', models.CharField(max_length=20, verbose_name='主机系统')),
                ('osVersion', models.CharField(max_length=20, verbose_name='系统版本')),
                ('disk', models.IntegerField(verbose_name='磁盘')),
                ('innerIP', models.CharField(max_length=16, verbose_name='内网IP')),
                ('outerIP', models.CharField(max_length=16, verbose_name='外网IP')),
                ('cloud', models.CharField(max_length=60, verbose_name='所属云')),
                ('region', models.CharField(max_length=60, verbose_name='所属区域')),
                ('status', models.CharField(max_length=1, verbose_name='主机状态（0正常 1已下线 2故障）')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('remark', models.CharField(max_length=128, verbose_name='备注')),
                ('hardwareId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asset.hardware')),
                ('proId', models.ForeignKey(default='999', on_delete=django.db.models.deletion.SET_DEFAULT, to='asset.project')),
            ],
        ),
    ]
