# Generated by Django 3.0.8 on 2020-07-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=32, verbose_name='角色名称')),
                ('roleKey', models.CharField(max_length=100, verbose_name='角色权限字符串')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='角色状态(0正常,1停用)')),
                ('delFlag', models.CharField(default='0', max_length=1, verbose_name='删除标识(0存在,1删除)')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createBy', models.CharField(default=None, max_length=32, verbose_name='创建者')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updateBy', models.CharField(default=None, max_length=32, verbose_name='更新者')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户账号')),
                ('password', models.CharField(max_length=64, verbose_name='用户密码')),
                ('nickName', models.CharField(max_length=64, null=True, verbose_name='用户昵称')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=64, null=True, verbose_name='邮箱')),
                ('sex', models.CharField(default='0', max_length=1, verbose_name='用户性别（0男 1女 2未知')),
                ('avatar', models.CharField(max_length=100, null=True, verbose_name='头像地址')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='用户状态(0正常,1停用)')),
                ('delFlag', models.CharField(default='0', max_length=1, verbose_name='删除标识(0存在,1删除)')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('loginTime', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
                ('LastLoginTime', models.DateTimeField(auto_now=True, verbose_name='最后时间')),
                ('loginIP', models.CharField(max_length=16, null=True, verbose_name='登录IP')),
                ('count', models.IntegerField(null=True, verbose_name='登录次数')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='备注')),
                ('roles', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='userAuth.Role')),
            ],
            options={
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userAuth.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('parentId', models.IntegerField(default=0, verbose_name='父菜单ID')),
                ('orderNum', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('path', models.CharField(default=None, max_length=200, verbose_name='路由地址')),
                ('component', models.CharField(default=None, max_length=255, verbose_name='组件路径')),
                ('isFrame', models.IntegerField(default=1, verbose_name='是否为外链(0是 1否)')),
                ('menuType', models.CharField(default=None, max_length=1, verbose_name='菜单类型（M目录 C菜单 F按钮）')),
                ('hidden', models.CharField(default='0', max_length=1, verbose_name='菜单显示状态（0显示 1隐藏）')),
                ('perms', models.CharField(default=None, max_length=100, verbose_name='权限标识')),
                ('icon', models.CharField(default='#', max_length=100, verbose_name='菜单图标')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createBy', models.CharField(default=None, max_length=32, verbose_name='创建者')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updateBy', models.CharField(default=None, max_length=32, verbose_name='更新者')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='备注')),
                ('role', models.ManyToManyField(to='userAuth.Role')),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
    ]
